#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/..
source test/config

name=${1:-dc1}
replicas=${2:-1}

./test/aks/create-storage-secret
./test/lib/deploy-operator
./test/lib/deploy-elassandra-with-storage ${name} ${replicas}
./test/lib/wait-dc-ready ${name} ${replicas}
./test/lib/check-dc-ok ${name} ${replicas}
