#!/usr/bin/env bash

set -xe

#
# To be sourced by other scripts
#

if [ "$_CONFIG_SOURCED" != "true" ]; then
  export _CONFIG_SOURCED="true"
else
  return 0
fi

export RESOURCE_GROUP=${RESOURCE_GROUP:-ci-staging}
export AZURE_REGION=${AZURE_REGION:-westeurope}

export AKS_NAME=${AKS_NAME:-testcluster2}
export AKS_NODE_COUNT=${AKS_NODE_COUNT:-3}
# the az service principal that will be used by the aks cluster, not the one used to create it.
export AKS_SP_ID=${AKS_SP_ID:-}
export AKS_SP_PASSWORD=${AKS_SP_PASSWORD:-}
export AKS_K8S_VERSION=${AKS_K8S_VERSION:-1.13.7}

export PULL_SECRET=${PULL_SECRET:-""}
export IMAGE_PREFIX=${IMAGE_PREFIX:-"strapdata/strapkop-"}
export IMAGE_SUFFIX=${IMAGE_SUFFIX:-"-dev"}
export ELASSANDRA=${ELASSANDRA:-elassandra}
# used for pull-secret registry
export REGISTRY=${REGISTRY:-docker.repo.strapdata.com}
export REGISTRY_USER=${REGISTRY_USER:-""}
export REGISTRY_PASSWORD=${REGISTRY_PASSWORD:-""}
export ELASSANDRA_IMAGE=${IMAGE_PREFIX}elassandra${IMAGE_SUFFIX}
export OPERATOR_IMAGE=${IMAGE_PREFIX}operator${IMAGE_SUFFIX}
export SIDECAR_IMAGE=${IMAGE_PREFIX}sidecar${IMAGE_SUFFIX}

SHA1=`git rev-parse --short HEAD`
export TAG="${TAG:-${SHA1}}"
#export TAG="${TAG:-latest}"

export SSL=${SSL:-true}
export AUTHENTICATION=${AUTHENTICATION:-CASSANDRA}
export ENTERPRISE=${ENTERPRISE:-true}

[ "$SSL" = "true" ] && [ "$ENTERPRISE" = "true" ] && export PROTOCOL="https" || export PROTOCOL="http"

# Azure storage
export AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT:-$(echo ${AKS_NAME} | sed 's/-//g')}
export AZURE_STORAGE_CONTAINER=${AZURE_STORAGE_CONTAINER:-testcontainer}
export AZURE_STORAGE_SECRET=${AZURE_STORAGE_SECRET:-azure-storage}

export ELASTICSEARCH_ENABLED=${ELASTICSEARCH_ENABLED:-true}

export NUM_RACKS=3
export DEFAULT_NAME=cluster-dc1

export PULL_POLICY_ELASSANDRA=${PULL_POLICY_ELASSANDRA:-IfNotPresent}
export PULL_POLICY_OPERATOR=${PULL_POLICY_OPERATOR:-IfNotPresent}
