#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/..
source test/config

./test/lib/undeploy-operator || true
kubectl delete sts --all --force --grace-period=0
kubectl delete pod --all --force --grace-period=0
kubectl delete svc --all --force --grace-period=0
kubectl delete edc --all || true
kubectl delete crd --all
kubectl delete pvc --all
kubectl delete pv --all
kubectl delete cm --all
kubectl delete secret --all
helm ls --all --short | xargs -L1 helm delete --purge || true
