#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/..
source test/config

./test/aks/create-cluster
./test/aks/get-credentials
./test/lib/configure-helm
./test/lib/create-pull-secret
./test/aks/create-storage

