#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/..
source strap-test/config

./strap-test/aks/create-cluster
./strap-test/aks/get-credentials
./strap-test/lib/configure-helm
./strap-test/lib/create-pull-secret
./strap-test/aks/create-storage

