#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/..
source test/config

./test/test-basic ${DEFAULT_NAME} 3
./test/test-scale ${DEFAULT_NAME} 1 3
./test/test-scale ${DEFAULT_NAME} 3 1
./test/test-backup ${DEFAULT_NAME} 3
./test/test-add-dc cluster dc1 dc3 3 1