#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/..
source test/config

name=${1:-${DEFAULT_NAME}}
from=${2:-1}
to=${3:-2}


./test/lib/deploy-operator


./test/lib/deploy-elassandra ${name} ${from}
./test/lib/wait-dc-ready ${name} ${from}
./test/lib/check-dc-ok ${name} ${from}
./test/lib/insert-basic-dataset ${name} ${from}
./test/lib/assert-basic-dataset ${name} ${from}

if ((${from} >= ${to})); then
  pod_list="$(./test/lib/list-pod-names ${name})"
fi

./test/lib/scale-elassandra ${name} ${to}
./test/lib/wait-dc-ready ${name} ${to}
./test/lib/check-dc-ok ${name} ${to}
./test/lib/assert-basic-dataset ${name} ${to}

if ((${from} < ${to})); then
  pod_list="$(./test/lib/list-pod-names ${name})"
fi

./test/lib/undeploy-elassandra ${name}
./test/lib/wait-dc-undeploy ${name} "$pod_list"
./test/lib/delete-dc-pvc ${name} "$pod_list"

./test/lib/undeploy-operator
