#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/..
source test/config

name=${1:-${DEFAULT_NAME}}
replicas=${2:-1}
backup_name=${3:-testbackup-${name}-$(date +'%s')}
rf=${4:-1}
size=${5:-10}

# requirement : azure storage created

./test/aks/create-storage-secret
./test/lib/deploy-operator
./test/lib/deploy-elassandra-with-storage ${name} ${replicas}
./test/lib/wait-dc-ready ${name} ${replicas}
./test/lib/check-dc-ok ${name} ${replicas}

./test/lib/insert-basic-dataset ${name} ${replicas} ${rf} ${size}
./test/lib/create-backup ${name} ${replicas} ${backup_name}

pod_list="$(./test/lib/list-pod-names ${name})"
./test/lib/undeploy-elassandra ${name}
./test/lib/wait-dc-undeploy ${name} "$pod_list"
./test/lib/delete-dc-pvc ${name} "$pod_list"


./test/lib/deploy-elassandra-from-backup ${name} ${replicas} ${backup_name}
./test/lib/wait-dc-ready ${name} ${replicas}
./test/lib/check-dc-ok ${name} ${replicas}

./test/lib/assert-basic-dataset ${name} ${replicas} ${size}

pod_list="$(./test/lib/list-pod-names ${name})"
./test/lib/undeploy-elassandra ${name}
./test/lib/wait-dc-undeploy ${name} "$pod_list"
./test/lib/delete-dc-pvc ${name} "$pod_list"

kubectl delete et ${backup_name}

./test/lib/undeploy-operator