#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/..
source strap-test/config

name=${1:-dc1}
from=${2:-1}
to=${3:-2}


./strap-test/lib/deploy-operator


./strap-test/lib/deploy-elassandra ${name} ${from}
./strap-test/lib/wait-dc-ready ${name} ${from}
./strap-test/lib/check-dc-ok ${name} ${from}
./strap-test/lib/insert-basic-dataset ${name} ${from}
./strap-test/lib/assert-basic-dataset ${name} ${from}

./strap-test/lib/scale-elassandra ${name} ${to}
./strap-test/lib/wait-dc-ready ${name} ${to}
./strap-test/lib/check-dc-ok ${name} ${to}
./strap-test/lib/assert-basic-dataset ${name} ${to}

./strap-test/lib/undeploy-elassandra ${name}
./strap-test/lib/wait-dc-undeploy ${name} ${to}
./strap-test/lib/delete-dc-pvc ${name} ${to}

./strap-test/lib/undeploy-operator
