#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/..
source test/config

cluster=${1:-cluster}
dc1=${2:-dc1}
dc2=${3:-dc2}
replicas1=${4:-1}
replicas2=${5:-1}

name1=${cluster}-${dc1}
name2=${cluster}-${dc2}

./test/lib/deploy-operator

# deploy first dc
./test/lib/deploy-elassandra ${name1} ${replicas1}
./test/lib/wait-dc-ready ${name1} ${replicas1}
./test/lib/check-dc-ok ${name1} ${replicas1}

# insert data
./test/lib/insert-basic-dataset ${name1} ${replicas1}
./test/lib/assert-basic-dataset ${name1} ${replicas1}

# deploy 2nd dc
./test/lib/deploy-new-dc ${name2} ${replicas2} elassandra-${name1}-seeds
./test/lib/wait-dc-ready ${name2} ${replicas2}
./test/lib/check-dc-ok ${name2} ${replicas2}

# assert data in 2nd dc
./test/lib/assert-basic-dataset ${name2} ${replicas2}

# remove first dc
./test/lib/undeploy-elassandra ${name1}
./test/lib/wait-dc-undeploy ${name1} ${replicas1}
./test/lib/delete-dc-pvc ${name1} ${replicas1}

# TODO: assert again data in 2nd dc
# ./test/lib/assert-basic-dataset ${name2} ${replicas2}

# remove second dc
./test/lib/undeploy-elassandra ${name2}
./test/lib/wait-dc-undeploy ${name2} ${replicas2}
./test/lib/delete-dc-pvc ${name2} ${replicas2}

./test/lib/undeploy-operator
