#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/..
source test/config

name=${1:-${DEFAULT_NAME}}
replicas=${2:-1}

./test/lib/deploy-operator
./test/lib/deploy-elassandra ${name} ${replicas}
./test/lib/wait-dc-ready ${name} ${replicas}
./test/lib/check-dc-ok ${name} ${replicas}

pod_list="$(./test/lib/list-pod-names ${name})"
./test/lib/undeploy-elassandra ${name}
./test/lib/wait-dc-undeploy ${name} "$pod_list"
./test/lib/delete-dc-pvc ${name} "$pod_list"

./test/lib/undeploy-operator