#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source strap-test/config

account_name=${AZURE_STORAGE_ACCOUNT:-strapdataoperatortest}
container_name=${AZURE_STORAGE_CONTAINER:-testcontainer}
secret_name=${AZURE_STORAGE_SECRET:-azure-storage}

az storage account create \
    --name ${account_name} \
    --resource-group ${RESOURCE_GROUP} \
    --location ${AZURE_REGION} \
    --sku Standard_LRS \
    --kind StorageV2

export access_key=$(az storage account keys list --account-name ${account_name} --resource-group ${RESOURCE_GROUP} --output json | jq -r '.[0].value')
az storage container create --name ${container_name} --account-name ${account_name} --account-key=${access_key}

./strap-test/aks/create-storage-secret