#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source strap-test/config

account_name=${AZURE_STORAGE_ACCOUNT:-strapdataoperatortest}
secret_name=${AZURE_STORAGE_SECRET:-azure-storage}

export access_key=$(az storage account keys list --account-name ${account_name} --resource-group ${RESOURCE_GROUP} --output json | jq -r '.[0].value')

echo -n ${account_name} > ./accountName
echo -n ${access_key} > ./accessKey
kubectl create secret generic ${secret_name} --from-file=./accountName --from-file=./accessKey --save-config --dry-run -o yaml | kubectl apply -f -
rm accountName accessKey
