#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

az aks create \
  -g ${RESOURCE_GROUP} \
  -n ${AKS_NAME} \
  --node-count ${AKS_NODE_COUNT} \
  --generate-ssh-keys \
  --kubernetes-version ${AKS_K8S_VERSION} \
  -l ${AZURE_REGION} \
  --service-principal ${AKS_SP_ID} \
  --client-secret ${AKS_SP_PASSWORD} \
  --verbose