#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

account_name=${AZURE_STORAGE_ACCOUNT:-strapdataoperatortest}
container_name=${AZURE_STORAGE_CONTAINER:-testcontainer}

az storage account delete --yes --name ${account_name} ||
./test/aks/delete-storage-secret