#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

dc_name=${1:-${DEFAULT_NAME}}
replicas=${2:-1}

cred=$(./test/lib/get-credentials-from-secret ${name})
cql_cred="$(./test/lib/to-cql-cred ${cred})"
curl_cred="$(./test/lib/to-curl-cred ${cred})"


for ((i=0; i<${replicas}; i++)); do
  node=$(./test/lib/get-pod-name ${dc_name} ${i})
  kubectl exec ${node} -c ${ELASSANDRA} -- cqlsh ${node} ${cql_cred} -e 'SHOW HOST'
  [ "$ELASTICSEARCH_ENABLED" = "true" ] && kubectl exec ${node} -c ${ELASSANDRA} -- curl ${curl_cred} ${PROTOCOL}://localhost:9200
  kubectl exec ${node} -c ${ELASSANDRA} -- nodetool status
done
