#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

name=${1:-dc1}

kubectl create secret generic ${name} \
  --from-file=keystore.jks=./test/resources/gen/${name}.jks \
  --from-file=./test/resources/gen/truststore.jks \
  --from-file=./test/resources/gen/cacert.pem \
  --dry-run -o yaml | kubectl apply -f -

# Set debug options
# JVM_OPTS="${JVM_OPTS} -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"