#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

index=${1:-ks}
type=${2:-t}
name=${3:-${DEFAULT_NAME}}
replicas=${4:-1}

node_0=$(./test/lib/get-pod-name ${name} 0)

cred=$(./test/lib/get-credentials-from-secret ${name})
curl_cred="$(./test/lib/to-curl-cred ${cred})"

if [ "$ELASTICSEARCH_ENABLED" = "true" ]; then

  es_resp=$(kubectl exec ${node_0} -c ${ELASSANDRA} -- curl -X PUT -H 'Content-Type: application/json' ${curl_cred} ${PROTOCOL}://localhost:9200/${index} -d'
  {
    "mappings": {
      "'${type}'": {
        "discover": ".*"
      }
    }
  }')
  echo "$es_resp"

  if ! echo "$es_resp" | grep '"acknowledged":true'; then
    echo "$es_resp" | grep resource_already_exists_exception || exit 1
  fi
fi