#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source strap-test/config

cacert=strap-test/resources/gen/cacert.pem
cakey=strap-test/resources/gen/cakey.pem


openssl rsa -in ${cakey} -out ${cakey}-unc -passin pass:changeit

kubectl create secret tls ca-key-pair \
   --cert=${cacert} \
   --key=${cakey}-unc \
   --namespace=default \
   --dry-run -o yaml | kubectl apply -f -

rm ${cakey}-unc

cat <<EOF | kubectl apply -f -
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: default
spec:
  ca:
    secretName: ca-key-pair
EOF