#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

name=${1:-${DEFAULT_NAME}}
replicas=${2:-1}
backup_name=${3:-testbackup-${dc}}

cat <<EOF | kubectl create -f -
apiVersion: stable.strapdata.com/v1
kind: ElassandraBackup
metadata:
  name: ${backup_name}
spec:
  selector:
    matchLabels:
      elassandra-operator.strapdata.com/cluster: $(./test/lib/get-cluster-name ${name})
      elassandra-operator.strapdata.com/datacenter: $(./test/lib/get-dc-name ${name})
  backupType: "AZURE_BLOB"
  target: ${AZURE_STORAGE_CONTAINER}
EOF

for ((i=0; i<${replicas}; i++)); do
  while true; do
    echo "waiting for pod backups to finish on node $i"
    kubectl logs $(./test/lib/get-pod-name ${name} ${i}) sidecar --tail=10
    if kubectl logs $(./test/lib/get-pod-name ${name} ${i}) sidecar --tail=10 | grep "Cleared snapshot \"$backup_name\""; then
      break;
    elif kubectl logs $(./test/lib/get-pod-name ${name} ${i}) sidecar --tail=20 | grep "ERROR"; then
      exit 1
    fi
    sleep 1
  done
done