#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source strap-test/config

kubectl create secret docker-registry ${PULL_SECRET} \
  --docker-server=${REGISTRY} \
  --docker-email="ci-staging@strapdata.com" \
  --docker-username=${REGISTRY_USER} \
  --docker-password=${REGISTRY_PASSWORD}
