#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

name=${1:-${DEFAULT_NAME}}
replicas=${2:-1}

# delete zombies pvc
for ((i=0; i<${replicas}; i++)); do
  kubectl delete pvc data-volume-$(./test/lib/get-pod-name ${name} ${i}) || true
done

# hopefully this will only delete pv that are Released...
# kubectl delete pv --all || true