#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

name=${1:-${DEFAULT_NAME}}
pod_list=$2

# delete zombies pvc
for pod in ${pod_list}; do
  kubectl delete pvc data-volume-${pod} || true
done
