#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

name=${1:-dc1}
replicas=${2:-1}

# delete zombies pvc
for ((i=0; i<${replicas}; i++)); do
  kubectl delete pvc elassandra-data-volume-${name}-elassandra-${i}
done