#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

name=${1:-cluster-dc2}
replicas=${2:-1}
remoteSeeds=${3:-"elassandra-cluster-dc1-seeds"}

helm_cmd="install --wait -n ${name}"
[ "${UPGRADE}" = "true" ] && helm_cmd="upgrade ${name}"

cat <<EOF | ./test/lib/deploy-elassandra  "$name" "$replicas" -
remoteSeeds: [${remoteSeeds}]
EOF