#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

cat <<EOF | ./test/lib/deploy-elassandra  "$1" "$2" -
env:
  - name: JVM_OPTS
    value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5001"
  - name: AZURE_STORAGE_ACCOUNT
    valueFrom:
      secretKeyRef:
        name: azure-storage
        key: accountName
  - name: AZURE_STORAGE_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: azure-storage
        key: accessKey
EOF