#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

helm_cmd="install --wait -n"
[ "${UPGRADE}" = "true" ] && helm_cmd="upgrade"

helm ${helm_cmd} elassandra-operator \
    --set image.repository=${OPERATOR_IMAGE} \
    --set-string image.tag=${TAG} \
    --set imagePullPolicy=${PULL_POLICY_OPERATOR} \
    --set imagePullSecret=${PULL_SECRET} \
    $@ \
    helm/elassandra-operator



for ((i=10; i>=1; i--)); do

  if kubectl get crd elassandradatacenters.stable.strapdata.com; then
    test/lib/wait-pod-ready $(test/lib/get-operator-pod-name)
    sleep 5 # some magic
    exit 0
  fi
  sleep 1

done



echo "ERROR: helm didn't create CRD"
exit 1