#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

helm install -n elassandra-operator --wait \
    --set image.repository=${OPERATOR_IMAGE} \
    --set image.tag=${TAG} \
    --set imagePullSecret=${PULL_SECRET} \
    $@ \
    helm/elassandra-operator


for ((i=10; i>=1; i--)); do

  if kubectl get crd elassandra-datacenters.stable.strapdata.com; then
    sleep 5 # some magic
    exit 0
  fi
  sleep 1

done



echo "ERROR: operator didn't create CRD"
exit 1