#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

name=${1:-${DEFAULT_NAME}}
index=${2:-0}

pod_name="$(kubectl get edc elassandra-cluster-dc1  -o json | jq '.status.podStatuses['${index}'].podName' -rc)"
if [[ "$pod_name" = "null" ]]; then
  exit 1
fi

echo "$pod_name"
