#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

dc_name=${1:-${DEFAULT_NAME}}

if [[ "$AUTHENTICATION" != "CASSANDRA" ]]; then
  echo -n ""
else
  username="strapkop"
  password="$(kubectl get secret $(./test/lib/get-cluster-name-prefix ${dc_name}) -o 'jsonpath={.data.cassandra.strapkop_password}' | base64 -d)"
  echo -n "$username:$password"
fi
