#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

dc_name=${1:-${DEFAULT_NAME}}
secret_name=${2:-strapkop}

if [[ "$AUTHENTICATION" != "CASSANDRA" ]]; then
  echo -n ""
else
  username="$(kubectl get secret $(./test/lib/get-name-prefix ${dc_name})-credentials-${secret_name} -o 'jsonpath={.data.username}' | base64 -d)"
  password="$(kubectl get secret $(./test/lib/get-name-prefix ${dc_name})-credentials-${secret_name} -o 'jsonpath={.data.password}' | base64 -d)"
  echo -n "$username:$password"
fi
