#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

name=${1:-${DEFAULT_NAME}}
index=${2:-0}

rack_name="rack$((index % ${NUM_RACKS} + 1))"
pod_index_in_rack="$(($index / ${NUM_RACKS}))"

echo "elassandra-${name}-${rack_name}-${pod_index_in_rack}"
