#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

name=${1:-${DEFAULT_NAME}}

for i in {1..${NUM_RACKS}}; do
  # TODO: add the possibility to pass label from DataCenterSpec to sts and pods
  kubectl patch sts elassandra-${name}-rack${i} -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
done