#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

name=${1:-${DEFAULT_NAME}}
replicas=${2:-1}

helm upgrade --reuse-values --set replicaCount=${replicas} ${name} helm/elassandra-datacenter