#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

cred=$1

if ! [[ -z "${cred}" ]]; then
  echo -n "-u $(echo "$cred" | cut -d ':'  -f 1) -p $(echo "$cred" | cut -d ':'  -f 2)"
fi