#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

pod_name=$(test/lib/get-operator-pod-name)

helm delete elassandra-operator --purge

if [[ "$pod_name" != "" ]]; then
  for ((i=60; i > 0; i--)); do
    echo "waiting for $pod_name to be terminated (#$i)"
    kubectl get pods
    if ! kubectl get pod ${pod_name}; then
      exit 0
    fi
    sleep 1
  done
fi

exit 1