#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

dc_name=${1:-${DEFAULT_NAME}}
pod_list=$2

is_pod_removed() {
  [[ "$(kubectl get po "$1" -o 'jsonpath={.status.conditions[?(@.type=="Ready")].status}')" == 'True' ]]

  if ! kubectl get pod "$1"; then
    return 0
  else
    return 1
  fi
}

wait_pod_removed(){
  for ((i=300; i>=1; i--)); do
    echo "waiting for pod $1 to be removed (#$i)"
    kubectl get pods
    is_pod_removed $1 && return 0
    sleep 1
  done
  return 1
}

# TODO: consistent naming

for pod in ${pod_list}; do
  wait_pod_removed ${pod}
done
