#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source test/config

dc_name=${1:-dc1}
replicas=${2:-1}

is_pod_ready() {
  [[ "$(kubectl get po "$1" -o 'jsonpath={.status.conditions[?(@.type=="Ready")].status}')" == 'True' ]]
}

wait_pod_ready(){
  for ((i=800; i>=1; i--)); do
    echo "waiting for pod $1 to be ready (#$i)"
    kubectl get pods
    is_pod_ready $1 && return 0
    sleep 1
  done
  return 1
}

# TODO: consistent naming

for ((x=0; x<${replicas}; x++)); do
  wait_pod_ready ${dc_name}-${CHART_NAME}-${x}
done

