#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source strap-test/config

name=${1:-dc1}

pkitool=strap-test/resources/pkitool
ca_store=strap-test/resources/gen/ca.p12
keystore=strap-test/resources/gen/${name}.jks

mkdir -p strap-test/resources/gen

$pkitool -subject CN="${name}" newkeystore \
  -storepass changeit \
  -keypass changeit \
  -dnsName 'localhost' \
  -ipAddr 127.0.0.1 \
  -dnsName '*'.elassandra-${name}-elassandra-seeds.default.svc.cluster.local \
  -keystore ${keystore} \
  -cakeystore ${ca_store} -castoretype PKCS12 \
  -castorepass changeit -cakeypass changeit

# echo | openssl s_client -showcerts -servername localhost -connect localhost:9200 2>/dev/null | openssl x509 -inform pem -noout -text