#!/usr/bin/env bash

cd `dirname "$BASH_SOURCE"`/../..
source strap-test/config

name=${1:-dc1}

mkdir -p strap-test/resources/gen
cd strap-test/resources/gen

find -type f -name "${name}*" -exec rm {} \;

#wilcard_name="*.elassandra-${name}-elassandra-seeds.default.svc.cluster.local"
wildcard_name="*.elassandra-${name}-elassandra-seeds.default.svc.toto.fr"

openssl_conf=$(mktemp)
cat <<EOF > ${openssl_conf}
[ CA_default ]
copy_extensions	= copy

[ req ]
distinguished_name     = req_distinguished_name
prompt                 = no
output_password        = changeit
default_bits           = 2048
req_extensions = v3_req

[ req_distinguished_name ]
C                      = FR
O                      = Strapdata
OU                     = Elassandra
CN                     = ${wildcard_name}

[v3_req]
subjectAltName = @san

[san]
DNS.1 = ${wildcard_name}
DNS.2 = localhost
IP.1 = 127.0.0.1
EOF

openssl req -new -newkey rsa:2048 -sha256 -nodes \
    -keyout ${name}.key \
    -config ${openssl_conf} \
    -out ${name}.csr -extensions v3_req

openssl x509 \
    -req \
    -CA cacert.pem \
    -CAkey cakey.pem \
    -in ${name}.csr \
    -out ${name}.crt_signed \
    -days 3650 \
    -CAcreateserial \
    -passin pass:changeit -extfile ${openssl_conf} -extensions v3_req


openssl verify -CAfile cacert.pem ${name}.crt_signed

openssl pkcs12 -export -name ${name} -in ${name}.crt_signed -inkey ${name}.key -out ${name}.p12 -passin pass:changeit -passout pass:changeit

keytool -import\
    -keystore ${name}.jks \
    -alias rootCa  \
    -file cacert.pem \
    -noprompt \
    -keypass changeit \
    -storepass changeit

keytool -importkeystore -destkeystore ${name}.jks -srckeystore ${name}.p12 -srcstoretype pkcs12 -alias ${name} -noprompt \
    -keypass changeit \
    -srcstorepass changeit \
    -storepass changeit

# openssl x509 -in dc1.crt_signed -text -noout
# openssl req -text -noout -verify -in dc1.csr
# openssl pkcs12 -info -in keyStore.p12
# keytool -list -v -keystore dc1.jks